### PR TITLE
Proposed fix for issue #37 #41 incl. legacy support

### PR DESCRIPTION
**Pull request by floriangeigl**
Basically the same fix as mentioned in https://github.com/fbradyirl/openwrt-luci-rpc/pull/41, but considering the concerns of @fbradyirl mentioned [here](https://github.com/fbradyirl/openwrt-luci-rpc/pull/41#issuecomment-743783222).

Does this sound better @fbradyirl ? Would love to get this in :) Also it's 2y later and most people will have moved to OpenWRT 18.+.

### CODE REVIEW

**Review by fbradyirl — APPROVED** [review]

**Comment by floriangeigl** [comment]
awesome - that was super-fast @fbradyirl 🚀 thanks so much - have a great sunday my friend 👋

**Comment by fbradyirl** [comment]
No worries. Thanks for the fix. I will try and release a new build this week and perhaps someone can open a PR to get it added to Home Assistant.

**Comment by floriangeigl** [comment]
perfect - I'm already on that too :) I'll include it in this [PR](https://github.com/home-assistant/core/pull/78176) for homeassistant.

**Comment by fbradyirl** [comment]
Ok v1.1.12 is released now.

**Comment by floriangeigl** [comment]
amazing 🚀 thx so much @fbradyirl 🙏

**Pull request merged**
