### PR TITLE
Proposed fix for issue #37

### PR DESCRIPTION
**Pull request by SBado**
Fix for [issue #37](https://github.com/fbradyirl/openwrt-luci-rpc/issues/37).

### CODE REVIEW

**Comment by tiagofreire-pt** [comment]
@SBado , could you rebase this, please?

**Comment by SBado** [comment]
Done.

**Comment by fbradyirl** [comment]
The worry I have here is that this change may break users on older versions of OpenWrt and this is untested.

I no longer use OpenWrt myself for device tracking so am sceptical to make any changes at this time. 

If anyone would like to take ownership of this repo, that is OK with me, I can transfer it to a confident developer.

**Comment by ben-64** [comment]
Without this fix, the device tracking is not anymore working on my side :(

**Comment by fbradyirl** [comment]
Fixed in #53

**Pull request closed without merging**
