### PR TITLE
Publish to pypi only once in github actions

### PR DESCRIPTION
**Pull request by pdecat**
Resolves an issue introduced in https://github.com/fbradyirl/openwrt-luci-rpc/pull/46#issuecomment-797529397

### CODE REVIEW

**Comment by fbradyirl** [comment]
Do we really need both 3.7 and 3.8? HA running with only 3.8 support will be able to install dependancies build with 3.7 just fine.

**Comment by pdecat** [comment]
The idea is to run unit tests for both python 3.7 and 3.8 but only build and publish the package with 3.8.

**Comment by fbradyirl** [comment]
I think you just need separate jobs for build and another for publish. 

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

Each job will have access to the same workspace as the previous so you should be fine to only publish as py37.

**Comment by pdecat** [comment]
Hi @fbradyirl,

> I think you just need separate jobs for build and another for publish.
> 
> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
> 
> Each job will have access to the same workspace as the previous so you should be fine to only publish as py37.

Well, jobs actually do not share the same workspace, only steps of the same job do:

> `jobs.<job_id>.steps`
A job contains a sequence of tasks called steps. Steps can run commands, run setup tasks, or run an action in your repository, a public repository, or an action published in a Docker registry. Not all steps run actions, but all actions run as a step. *Each step runs in its own process in the runner environment and has access to the workspace and filesystem*.

If jobs shared the same workspace, that would cause issues when jobs are executing concurrently.

See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps

Sharing artifacts between jobs requires to upload them in one job then download them in a following job.

See https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
and https://docs.github.com/en/actions/learn-github-actions/migrating-from-circleci-to-github-actions#persisting-data-between-jobs
and https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions#sharing-files-between-jobs-and-workflows

That's why I separated the test phases as concurrent jobs from the build and publish phase as a single job.

WDYT?

**Comment by fbradyirl** [comment]
Sounds good thanks @pdecat

**Review by fbradyirl — APPROVED** [review]

**Comment by pdecat** [comment]
I pushed two changes to:

1. fix an issue where using `env` in job strategy/matrix is not supported: https://github.com/actions/runner/issues/480#issuecomment-803270642
2. fix an issue that caused both `push` and `pull_request` event to trigger concurrent jobs, running the same tests twice: https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2

**Pull request merged**
