### PR TITLE
Support newer openwrt snapshot versions

### PR DESCRIPTION
**Pull request by pdecat**
This PR adds support for new snapshot versions like `21.02-snapshot`

### CODE REVIEW

**Comment by pdecat** [comment]
As I've not yet pushed the second commit that fixes the unit test, this check should have failed https://github.com/fbradyirl/openwrt-luci-rpc/pull/45/checks?check_run_id=2045983029

The following error occurs locally when running tox:

```
======================================================================
FAIL: test_is_legacy_version (tests.test_version.TestOpenwrtLuciRPC)
Test comparing versions works as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/patrick/workspaces/homeassistant/devices/openwrt/openwrt-luci-rpc/tests/test_version.py", line 34, in test_is_legacy_version
    assert is_legacy_version(version.parse("21.02-snapshot")) is False
AssertionError

----------------------------------------------------------------------
Ran 9 tests in 0.002s

```

**Comment by pdecat** [comment]
Fixed tox: https://github.com/fbradyirl/openwrt-luci-rpc/runs/2046085244?check_suite_focus=true#step:6:57

**Comment by pdecat** [comment]
Rebased on master following #46 merge.

**Review by fbradyirl — APPROVED** [review]
Looks good to me. 

Patrick, since I not longer use this module for my Home Assistant would you be interested in taking ownership of the integration and this repo?

**Comment by pdecat** [comment]
Hi @fbradyirl, thank you very much, I'd be glad to help maintaining this project. Just to clarify, are you proposing to transfer your repository under my [personal github account](https://github.com/pdecat)? If so, I'm wondering if the https://github.com/openwrt organization wouldn't be a better place. Have you ever approached its owners to see if this would interest them?

**Comment by fbradyirl** [comment]
Good idea. I haven't approached them but might be the best way. For now, I will add you add a collab on my repo here so you will have the same rights as me.  You can still add me to PRs for this project and Home Assistant but generally, since I don't rely on the integration, my testing is limited.

**Comment by pdecat** [comment]
What about creating a new release with the changes from this PR? I'd like then open a PR on Home Assistant to use it.

**Comment by fbradyirl** [comment]
@pdecat want to try and do the release yourself? You are a collaborator now on the project.

Steps:
* Update HISTORY.rst (new patch version 1.1.8)
* Commit that.
* To create a new tag use one of the command `bumpversion patch`. If major or minor you would use:

`bumpversion minor`
`bumpversion major`

* Then push 

`git push && git push --tags`

You should see Github Actions will push the new tag to pypi.

**Comment by pdecat** [comment]
Hi @fbradyirl, I followed your instructions but I do not have permissions to push to master:

```
# git log -n 3
commit d34af49640e399b178b7333d0dcbb2df99c78cad (HEAD -> master, tag: v1.1.8)
gpg: Signature made Fri 12 Mar 2021 01:41:22 PM CET
gpg:                using RSA key C9A6BD07A7089CE56CDF6125FD55B9BD5687D8FF
gpg: Good signature from "Patrick Decat <pdecat@gmail.com>" [ultimate]
Primary key fingerprint: 9779 4ADD 33EA 00D3 2389  8608 A811 66D9 F225 BAF8
     Subkey fingerprint: C9A6 BD07 A708 9CE5 6CDF  6125 FD55 B9BD 5687 D8FF
Author: Patrick Decat <pdecat@gmail.com>
Date:   Fri Mar 12 13:41:22 2021 +0100

    Bump version: 1.1.7 → 1.1.8

commit 78cce19c0def93c17a72efdde058ab26ced0d5cf
gpg: Signature made Fri 12 Mar 2021 01:38:30 PM CET
gpg:                using RSA key C9A6BD07A7089CE56CDF6125FD55B9BD5687D8FF
gpg: Good signature from "Patrick Decat <pdecat@gmail.com>" [ultimate]
Primary key fingerprint: 9779 4ADD 33EA 00D3 2389  8608 A811 66D9 F225 BAF8
     Subkey fingerprint: C9A6 BD07 A708 9CE5 6CDF  6125 FD55 B9BD 5687 D8FF
Author: Patrick Decat <pdecat@gmail.com>
Date:   Fri Mar 12 13:38:30 2021 +0100

    Update HISTORY for 1.1.8

commit e2f751f2147fc7e2e1536d67079c0c05835b6d01 (upstream/master, upstream/HEAD)
gpg: Signature made Sat 06 Mar 2021 08:27:33 PM CET
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Good signature from "GitHub (web-flow commit signing) <noreply@github.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 5DE3 E050 9C47 EA3C F04A  42D3 4AEE 18F8 3AFD EB23
Author: Patrick Decat <pdecat@gmail.com>
Date:   Sat Mar 6 20:27:33 2021 +0100

    Support newer openwrt snapshot versions (#45)
```

```
# git push
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 2.23 KiB | 2.23 MiB/s, done.
Total 9 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 6 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "build (3.7)" is expected.
To github.com:fbradyirl/openwrt-luci-rpc.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:fbradyirl/openwrt-luci-rpc.git'
```

**Comment by fbradyirl** [comment]
I think your permissions were OK. 

I just removed the master branch protection so can you try the push again?

**Comment by pdecat** [comment]
It worked :)

**Pull request merged**
